version: '3'

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/usr/src/app
      - node_modules_volume:/usr/src/app/oga-milestone/node_modules
    ports:
      - '3000:3000'
    tty: true
volumes:
  node_modules_volume:
    driver_opts:
      type: none
      device: ${PWD}/oga-milestone/node_modules
      o: bind