version: '3'

services:
  frontend:
    build: .
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - ./:/usr/src/app
    ports:
      - '3000:3000'
    tty: true